import { afterEach, expect, it, vi } from "vitest";
import { act, cleanup, renderHook, waitFor } from "@testing-library/react";
import { useTray } from "./useTray";
import { bridge } from "./bridge";
vi.mock("./bridge", () => ({ bridge: { trayAvailable: vi.fn(async () => true), onTrayPower: vi.fn() } }));
afterEach(() => { cleanup(); vi.clearAllMocks(); });
it("blocks unavailable shortcuts, uses current callback, and removes its listener", async () => {
  let handler!: (value: boolean) => void;
  const stop = vi.fn();
  vi.mocked(bridge.onTrayPower).mockImplementation(async (callback) => { handler = callback; return stop; });
  const first = vi.fn(async () => {});
  const next = vi.fn(async () => {});
  const view = renderHook(({ available, power }) => useTray(true, available, power), { initialProps: { available: false, power: first } });
  await waitFor(() => expect(bridge.onTrayPower).toHaveBeenCalledTimes(1));
  act(() => handler(true));
  expect(first).not.toHaveBeenCalled();
  view.rerender({ available: true, power: next });
  act(() => handler(false));
  expect(next).toHaveBeenCalledExactlyOnceWith(false);
  view.rerender({ available: false, power: next });
  act(() => handler(true));
  expect(next).toHaveBeenCalledTimes(1);
  view.unmount();
  expect(stop).toHaveBeenCalledOnce();
  act(() => handler(true));
  expect(next).toHaveBeenCalledTimes(1);
});
it("cleans up a late listener without accepting commands after unmount", async () => {
  let finish!: (stop: () => void) => void;
  let handler!: (value: boolean) => void;
  vi.mocked(bridge.onTrayPower).mockImplementation((callback) => { handler = callback; return new Promise((resolve) => { finish = resolve; }); });
  const power = vi.fn(async () => {});
  const stop = vi.fn();
  const view = renderHook(() => useTray(true, true, power));
  view.unmount();
  act(() => handler(true));
  await act(async () => finish(stop));
  expect(stop).toHaveBeenCalledOnce();
  expect(power).not.toHaveBeenCalled();
});
